@baseUrl=http://localhost:5000/auth

POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "petro@gmail.com",
    "password": "epicode"
}

###
GET {{baseUrl}}/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmUwOGM4ZGI5NmEzMDk2OTIyZDhjOTEiLCJ1c2VyRGF0YSI6eyJfaWQiOiI2NmUwOGM4ZGI5NmEzMDk2OTIyZDhjOTEiLCJuYW1lIjoicGV0cm8iLCJzdXJuYW1lIjoiZXBpY29kZSIsImVtYWlsIjoicGV0cm9AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkdmhZUi5jRmtVTi55OXpYNUVrVEpJdThOMTZqL3RrbGF0dE01akFkSThlZVhINWZUR1FGMzIiLCJyb2xlIjoiY2FsY2lhdG9yZSIsImRlc2NyaXB0aW9uIjoic29ubyBkaSBlcGljb2RlIiwiYXZhdGFyIjoiaHR0cHM6Ly90aHVtYnMuZHJlYW1zdGltZS5jb20vei9kaXNlZ25vLXZldHRvcmlhbGUtaW1tYWdpbmUtcHJvZmlsby1hdmF0YXItdnVvdG8tMjYyNjgzMDA5LmpwZz9jdD1qcGVnIiwiYmFja2dyb3VuZEltYWdlIjoiaHR0cHM6Ly90aHVtYnMuZHJlYW1zdGltZS5jb20vei9kaXNlZ25vLXZldHRvcmlhbGUtaW1tYWdpbmUtcHJvZmlsby1hdmF0YXItdnVvdG8tMjYyNjgzMDA5LmpwZz9jdD1qcGVnIiwiZXhwZXJpZW5jZXMiOltdLCJjcmVhdGVkQXQiOiIyMDI0LTA5LTEwVDE4OjE0OjM3LjIwNFoiLCJ1cGRhdGVkQXQiOiIyMDI0LTA5LTEwVDE4OjE0OjM3LjIwNFoiLCJfX3YiOjB9LCJpYXQiOjE3MjYwNzk5NTUsImV4cCI6MTcyNjA4MzU1NX0.44K2K2afUVjaFQDA6JFmWxYWkhFSqeVNSvGjiXb0ld8
Content-Type: application/json