###
POST http://localhost:5000/experiences
Content-Type: application/json

{
    "role": "petro",
    "company": "epicode",
    "startDate": "",
    "endDate": "",
    "area": "calciatore",
    "description": "sono di epicode"
}

###

GET http://localhost:5000/experiences/66e1d958671c6433be133845