###
POST http://localhost:5000/profile
Content-Type: application/json

{
    "name": "petro",
    "surname": "epicode",
    "email": "petro@gmail.com",
    "password":"epicode",
    "role": "calciatore",
    "description": "sono di epicode"
}

###
GET http://localhost:5000/profile?page=2

###
PUT http://localhost:5000/profile/66e083a64a38ac97498eb7db
Content-Type: application/json

{
    "name": "andrea",
    "surname": "epicode",
    "email": "roberto@gmail.com",
    "password":"elo",
    "description": "sono di epicode"
}

###
DELETE http://localhost:5000/profile/66e083a64a38ac97498eb7db
